// declare module "@components/*";
// declare module "@assets/*";
// declare module "@styles/*";
// declare module "@constants/*";
// declare module "@containers/*";
// declare module "@hooks/*";
// declare module "@services/*";
// declare module "@types/*";
// declare module "@utils/*";
